//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressValidation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressValidation
    {
        public int AddressValidationId { get; set; }
        public System.DateTime SysCreated { get; set; }
        public string SysCreatedBy { get; set; }
        public System.DateTime SysLastModified { get; set; }
        public string SysLastModifiedBy { get; set; }
        public int EnterpriseID { get; set; }
        public int UserID { get; set; }
        public string LoginID { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public int UserAddressID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> USPSValidationResult { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public string CleansedAddress1 { get; set; }
        public string CleansedAddress2 { get; set; }
        public string CleansedCity { get; set; }
        public string CleansedStateProvince { get; set; }
        public string CleansedPostalCode { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorSource { get; set; }
        public string ErrorDescription { get; set; }
        public string ErrorHelpFile { get; set; }
        public string ErrorHelpContext { get; set; }
    }
}
